default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: weather_task_development

test:
  <<: *default
  database: weather_task_test

production:
  <<: *default
  database: weather_task_production
  username: weather_task
  password: <%= ENV['WEATHER_TASK_DATABASE_PASSWORD'] %>
